### ISSUE TITLE
Dropdown needs to close on click elsewhere

### ISSUE THREAD

**Issue by vedmant** [creativetimofficial/david-ai#18]
Dropdown needs to close on click elsewhere

**Comment by EINazare** [comment]
Hello there, @vedmant ,

Yes, you are right, but at the moment we do not know how it would be best to do this.
If you have any idea, you can open a PR and if everything checks out, we'll approve it.

Best,
Manu

**Comment by Sensiblemnd** [comment]
https://medium.com/@kevinfelisilda/click-outside-element-event-using-react-hooks-2c540814b661

**Comment by acatzk** [comment]
I suggest you used @headless-ui for better functionality

**Comment by EINazare** [comment]
Hello there, @acatzk ,

The problem with Headless UI is the fact that it only comes with React & VueJS, and there would be differences between React, Angular, VueJS, and Vanilla JS. 
I think we should keep the same functionalities in all of our versions of this project.

Best,
Manu

**Comment by marqbeniamin** [comment]
@Priyanka11-dev thank you for your interest. Yes, you can create PR with your idea. I assign you this issue.
