### ISSUE TITLE
Suggestion: Symfony as a PHP alternative.

### ISSUE THREAD

**Issue by excitedbox** [creativetimofficial/david-ai#31]
Symfony is the biggest php framework out there with over 2 BILLION downloads and already offers tailwind integration but NO UI components. Offering a pre configured download of your starter kit components would make it easy for users to integrate them into their project.

As it stands right now Symfony only supplies the database, php, and template engine for your project and leaves out most of the front end UI stuff so having a set of components to use would be awesome.

Right now your project offers several JS options and I think it is great you also offer a pure HTML option with vanilla JS code, it would be great to see a php option offered as well. Starting from html still requires a ton of work building the interaction between the backend and UI, which can be overwhelming with an unfamiliar system and would require millions of developers to do the same integration over and over again.

**Comment by EINazare** [comment]
Hey @excitedbox ,

Thank you for sharing this information with us. We will try to add a PHP with Symfony version as soon as possible.

Best,
Manu

**Comment by excitedbox** [comment]
Awesome, I am looking forward to it. Like I said Symfony really lacks front end component frameworks and because they use the Twig template engine most integrations would need quite a bit of modification. I think the large user base makes it worth it though, especially since tailwind is picking up in popularity it would make a great addition.
