### ISSUE TITLE
Buttons don't have a focus state.

### ISSUE THREAD

**Issue by thetarnav** [creativetimofficial/david-ai#36]
I've noticed some elements, especially buttons, don't have a focus state styled. Buttons even have the default browser outline disabled, without anything in its place. Meaning users cannot navigate using the tab key.
Generally, it's not that big of a deal since it can be added easily, but I think some basic visual info should be added by default.
Anyway, thanks for an amazing elements kit!

**Comment by jodavid444** [comment]
I would like to work on this task, kindly assign it to me
