### ISSUE TITLE
Rename it to "Tailwind Open UI"

### ISSUE THREAD

**Issue by LouisGac** [creativetimofficial/david-ai#37]
Hello,

Your work is amazing for a newcomer to Tailwind, it really simplifies things. I believe that the basic CSS components should be part of the Tailwind library, as they are part of the Bootstrap library.  In fact, this was the case for version 1 of tailwind. But since version 2, they have become chargeable. In fact, your Starter Kit is becoming an open source version of TailwindUi. I invite you to rename it accordingly "tailwind open UI", it would make things clearer for newcomers, and it would certainly bring you a lot of participation on your repository. 

Anyway, thanks again for your great work.

**Comment by maitreyeepaliwal** [comment]
Hey. I am new to open source and Hacktoberfest.
I wanted to know that does this issue says that for all the web pages here, the word 'Tailwind Starter Kit' is to be renamed to 'tailwind open UI' .?
