### ISSUE TITLE
Can't resolve 'views/Dashboard.js'

### ISSUE THREAD

**Issue by mehulkundu** [creativetimofficial/david-ai#43]
In react-dashboard-page
When I run `npm start `
its giving this kind of error

```
./src/index.js
Module not found: Can't resolve 'views/Dashboard.js' in 'C:\Users\kundu\Desktop\Tailwind Starter kit\tailwind-starter-kit\Dashboard Page\react-dashboard-page\src'
```

**Comment by malaktayeh** [comment]
Try fetching the latest changes?  I just tried it out, and the project is running without error messages @mehulkundu
