### ISSUE TITLE
profile page responsiveness

### ISSUE THREAD

**Issue by mahmoud-bebars** [creativetimofficial/david-ai#51]
in the mobile view the connect button isn't responsive it goes to the left side

can be fixed if it takes all the width on the mobile view or to be centered when the width is small 
<img width="359" alt="Screen Shot 2022-03-17 at 23 44 41" src="https://user-images.githubusercontent.com/66588352/158900005-7210a061-b9f6-4a73-ba68-5b2baa2b60b5.png">

**Comment by vansh-attri** [comment]
Hi, Can you please assign me this issue?
